[build]
  command   = "yarn build && yarn export"
  publish   = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.master]
  [context.master.environment]
    ENVIRONMENT = "production"
    WEB_DEBUG = "false"
    GOOGLE_ANALYTICS_ENABLED = "true"
# Deploy Preview context: All Deploy Previews
# will inherit these settings.
#[context.deploy-preview.environment]
#  ACCESS_TOKEN = "not so secret"
